language: generic
matrix:
  include:
    - language: generic
      sudo: required
      services:
        - docker
      script: docker run -v $PWD:/walletcordova greenaddress/android_cordova@sha256:1632a1f7445de4650bd3d1420a08e1416e43e3ba59600dbb38fcecf7c0ae8d66

    - os: osx
      osx_image: xcode8.3
      before_script: sudo npm install -g cordova
      sudo: required
      install:
        - brew update > /dev/null
        - brew upgrade node
        - pip install virtualenv
      script:
        - ./prepare.sh
        - cordova prepare ios
        - cordova build ios

