language: generic
matrix:
  include:
    - language: generic
      sudo: required
      services:
        - docker
      script: docker run -v $PWD:/walletcordova greenaddress/android_cordova@sha256:cfe386fdfcb09842c11a7bc5f41f9ea9323abbd38e453512799e53decc364e5c

    - os: osx
      osx_image: xcode8.3
      before_script: sudo npm install -g cordova
      sudo: required
      install:
        - brew update > /dev/null
        - brew upgrade node
        - pip install virtualenv
      script:
        - ./prepare.sh
        - cordova prepare ios
        - cordova build ios

